apiVersion: v1
kind: Service
metadata:
  name: springboot-devsecops
  namespace: springboot-devsecops
spec:
  type: ClusterIP

  selector:
    app: springboot-devsecops

  ports:
    - name: http
      port: 8080
      targetPort: 8080